#!/usr/bin/env python3
"""Verify migration checksums and generate atomic SQL Editor bundles."""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import NoReturn

ROOT = Path(__file__).resolve().parents[2]
MIGRATIONS = ROOT / "migrations"
MANIFEST = MIGRATIONS / "manifest.sha256"
ENTRY = re.compile(r"^([0-9a-f]{64})  (([0-9]{4})_[A-Za-z0-9_.-]+\.sql)$")
SQL_NAME = re.compile(r"^([0-9]{4})_[A-Za-z0-9_.-]+\.sql$")


@dataclass(frozen=True)
class Migration:
    version: str
    filename: str
    checksum: str
    path: Path


def fail(message: str) -> NoReturn:
    raise ValueError(message)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def load_manifest() -> list[Migration]:
    if not MANIFEST.is_file():
        fail(f"missing manifest: {MANIFEST.relative_to(ROOT)}")
    items: list[Migration] = []
    seen_files: set[str] = set()
    seen_versions: set[str] = set()
    for line_number, raw in enumerate(MANIFEST.read_text(encoding="utf-8").splitlines(), 1):
        match = ENTRY.fullmatch(raw)
        if not match:
            fail(f"malformed manifest line {line_number}")
        checksum, filename, version = match.groups()
        if filename in seen_files or version in seen_versions:
            fail(f"duplicate migration at manifest line {line_number}")
        seen_files.add(filename)
        seen_versions.add(version)
        items.append(Migration(version, filename, checksum, MIGRATIONS / filename))
    if not items:
        fail("manifest is empty")
    return items


def verify(base_ref: str | None = None) -> list[Migration]:
    items = load_manifest()
    sql_files = sorted(path.name for path in MIGRATIONS.glob("*.sql"))
    manifest_files = [item.filename for item in items]
    if manifest_files != sql_files:
        missing = sorted(set(sql_files) - set(manifest_files))
        extra = sorted(set(manifest_files) - set(sql_files))
        fail(f"manifest/file mismatch: missing={missing}, extra={extra}")
    expected_versions = [f"{number:04d}" for number in range(1, len(items) + 1)]
    versions = [item.version for item in items]
    if versions != expected_versions:
        fail(f"migration versions must be contiguous: got {versions}")
    for item in items:
        name_match = SQL_NAME.fullmatch(item.filename)
        if not name_match or name_match.group(1) != item.version:
            fail(f"invalid migration filename: {item.filename}")
        actual = sha256(item.path.read_bytes())
        if actual != item.checksum:
            fail(f"checksum mismatch: {item.filename}")
    if base_ref:
        verify_historical_immutability(base_ref)
    return items


def git(*args: str) -> bytes:
    return subprocess.check_output(["git", *args], cwd=ROOT, stderr=subprocess.STDOUT)


def verify_historical_immutability(base_ref: str) -> None:
    try:
        paths = git("ls-tree", "-r", "--name-only", base_ref, "migrations").decode().splitlines()
    except subprocess.CalledProcessError as error:
        fail(f"unable to read base ref {base_ref}: {error.output.decode(errors='replace').strip()}")
    for relative in paths:
        filename = Path(relative).name
        if not SQL_NAME.fullmatch(filename):
            continue
        current = ROOT / relative
        if not current.is_file():
            fail(f"historical migration deleted or renamed: {relative}")
        try:
            historical = git("show", f"{base_ref}:{relative}")
        except subprocess.CalledProcessError:
            fail(f"unable to read historical migration: {relative}")
        if current.read_bytes() != historical:
            fail(f"historical migration modified: {relative}")


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_bundle(
    items: list[Migration],
    apply: list[Migration],
    register: list[Migration],
    attest: list[Migration] | None = None,
) -> str:
    sections = [
        "-- Generated by .github/scripts/migration-ledger.py; review before Supabase SQL Editor execution.",
        "BEGIN;",
        "SELECT pg_advisory_xact_lock(hashtext('portfolio-backend-2026:migrations'));",
    ]
    if attest:
        expected = ",\n".join(
            f"        ({sql_literal(item.version)}, {sql_literal(item.filename)}, {sql_literal(item.checksum)})"
            for item in attest
        )
        sections.extend([
            "\nDO $ledger_attestation$",
            "BEGIN",
            f"    IF (SELECT count(*) FROM \"PortfolioMigration\") <> {len(attest)} OR EXISTS (",
            "        SELECT 1",
            "        FROM (VALUES",
            expected,
            "        ) AS expected(version, filename, checksum)",
            "        LEFT JOIN \"PortfolioMigration\" AS applied USING (version)",
            "        WHERE applied.version IS NULL",
            "           OR applied.\"filename\" <> expected.filename",
            "           OR applied.\"checksum\" <> expected.checksum",
            "    ) THEN",
            "        RAISE EXCEPTION 'existing migration ledger does not match the reviewed baseline';",
            "    END IF;",
            "END;",
            "$ledger_attestation$;",
        ])
    for item in apply:
        sections.extend([f"\n-- BEGIN {item.filename}", item.path.read_text(encoding="utf-8"), f"-- END {item.filename}"])
    if register:
        values = ",\n".join(
            f"    ({sql_literal(item.version)}, {sql_literal(item.filename)}, {sql_literal(item.checksum)})"
            for item in register
        )
        sections.extend([
            "\nINSERT INTO \"PortfolioMigration\" (\"version\", \"filename\", \"checksum\") VALUES",
            values + ";",
        ])
    sections.extend(["COMMIT;", ""])
    return "\n".join(sections)


def select_versions(items: list[Migration], versions: list[str]) -> list[Migration]:
    by_version = {item.version: item for item in items}
    unknown = [version for version in versions if version not in by_version]
    if unknown:
        fail(f"unknown migration versions: {unknown}")
    selected = [by_version[version] for version in versions]
    if [item.version for item in selected] != sorted(item.version for item in selected):
        fail("versions must be provided in ascending order")
    return selected


def write_output(content: str, output: str | None) -> None:
    if output:
        path = Path(output)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(path.resolve())
    else:
        sys.stdout.write(content)


def main() -> int:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)

    verify_parser = subparsers.add_parser("verify")
    verify_parser.add_argument("--base-ref")

    bundle_parser = subparsers.add_parser("bundle")
    bundle_parser.add_argument("--versions", nargs="+", required=True)
    bundle_parser.add_argument("--output")

    bootstrap_parser = subparsers.add_parser("bootstrap")
    bootstrap_parser.add_argument("--baseline-through", required=True)
    bootstrap_parser.add_argument("--through", required=True)
    bootstrap_parser.add_argument("--output")

    args = parser.parse_args()
    try:
        items = verify(getattr(args, "base_ref", None))
        if args.command == "verify":
            print(f"migration manifest verified: {len(items)} migrations")
            return 0
        if args.command == "bundle":
            selected = select_versions(items, args.versions)
            write_output(render_bundle(items, selected, selected), args.output)
            return 0
        baseline = int(args.baseline_through)
        through = int(args.through)
        if baseline < 0 or through <= baseline:
            fail("bootstrap requires through > baseline-through")
        apply = [item for item in items if baseline < int(item.version) <= through]
        if not apply:
            fail("bootstrap apply range is empty")
        ledger_version = 21
        if baseline < ledger_version:
            if not any(item.filename == "0021_migration_ledger.sql" for item in apply):
                fail("bootstrap apply range must include 0021_migration_ledger.sql")
            register = [item for item in items if int(item.version) <= through]
            attest = None
        else:
            register = apply
            attest = [item for item in items if int(item.version) <= baseline]
        write_output(render_bundle(items, apply, register, attest), args.output)
        return 0
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(f"migration-ledger: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
